language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "4.1"
before_install:
  - npm install -g npm@'>=3'
before_script:
  - npm install -g gulp
  - npm run typings
script:
  - gulp lint
  - gulp build:nolint
branches:
  only:
    - es6